### ISSUE TITLE
Infix -> Prefix

### ISSUE THREAD

**Issue by BananaObserved** [Clojure-Intro-Course/UsabilityStudy#1]
Early in the document you mention racket using infix notation, but it actually uses prefix notation.  Infix notation refers to putting the operator between the operands, for example (3 + 4), while prefix refers to putting the operator between the operands, such as (+ 3 4).  Prefix notation is sometimes also called Polish notation.

**Comment by elenam** [comment]
Good catch, thanks! I've made this mistake several times this year :-(
