### ISSUE TITLE
List format

### ISSUE THREAD

**Issue by BananaObserved** [Clojure-Intro-Course/UsabilityStudy#3]
In all examples of lists, you list the output format as (list 2 3 0).  However, unless I remember wrong, under default settings that list would be returned as (cons 2 (cons 3 (cons 0 empty))).  Should we make any mention of this or change the settings, or is list compression included in intermediate?

**Comment by elenam** [comment]
Intermediate w/lambda displays them as (list ...). The results are directly copied from the interpreter.
