### ISSUE TITLE
Target level?

### ISSUE THREAD

**Issue by BananaObserved** [Clojure-Intro-Course/UsabilityStudy#4]
The target level for the audience seems inconsistent.  For example, you define predicates and structures, which are fairly basic, so it seems aimed at new programmers.  However, very early on, you mention strings without defining them.  To non-programmers, the phrase "string" as it is used in computer science is very unintuitive.  Should one of these be changed?

**Comment by elenam** [comment]
This is a review, not an introduction. The study subjects have taken the Racket class.
